# Generated by Django 5.2.5 on 2025-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_studentmark_subjectmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
