# Generated by Django 5.2.5 on 2025-10-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_student_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
